version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: test_db
      # MYSQL_USER: devuser
      # MYSQL_PASSWORD: devpass
    ports:
      - "2000:3306"
    volumes:
     - /home/manonmaie/Downloads/QM/QuizMakerdb_create.sql:/docker-entrypoint-initdb.d/create.sql

  web_php:
    build: .
    container_name: web_QuizMaker
    depends_on:
      - db
    volumes:
      - /var/www/html/QuizMaker_se:/var/www/html/
    ports:
      - "2001:80"
    stdin_open: true
    tty: true
